### PR TITLE
add flag to skip renderer's bounding box intersection

### PR DESCRIPTION
**Pull request by bogovicj**
a default implementation preserves the current behavior

### CODE REVIEW

**Comment by bogovicj** [comment]
See https://github.com/bigdataviewer/bigdataviewer-vistools/pull/47 for an example

**Comment by bogovicj** [comment]
Other, specialized implementations can override the method I added as appropriate (i.e. [`WarpedSource`](https://github.com/saalfeldlab/bigwarp/blob/master/src/main/java/bdv/img/WarpedSource.java)) but for Source implementations in bdv-core and bdv-vistools it's less clear to me:
* which `Source`s should have an immutable flag set in the constructor?
* which `Source`s (if any) need a set method for this flag?

**Comment by axtimwalde** [comment]
Which `Source`s are in question?
* `AbstractSpimSource` default true
* `RealRandomAccessibleSource` final flag, default false
* `TransformedBoxPlaceHolderSource` default true
* `TransformedSource` defined by source

**Comment by axtimwalde** [comment]
In vistools, generally:
`Interval` sources default true
non-`Interval` sources final flag, default false

**Comment by bogovicj** [comment]
Ready to go.  Most sources default to `true` - i.e. do the bounding box check. The exceptions are:
* `RealRandomAccessibleSource`
* `RealRandomIntervalAccessibleSource` (vistools)
* `RandomAccessibleSource` (vistools)
* `RandomAccessibleSource4D` (vistools)
* `TransformedSource` behavior is defined by the source it wraps

The default behavior for these exceptions is to skip the bounding box check, but new constructors enable the programmer to set the flag manually.

**Comment by NicoKiaru** [comment]
What do you think of adding getters / setters if we want to modify the behaviour after the `Source` is created ? Also just curiosity : will it behave the same way between `Volatile` and non-`Volatile` sources ?

**Comment by axtimwalde** [comment]
This can be done at a later time because it is not in the way of the current behavior.  This PR fixes false behavior, namely not rendering infinite sources or sources for which bounding box calculation is costly and therefore not accurate.

**Comment by axtimwalde** [comment]
> will it behave the same way between Volatile and non-Volatile sources ?
Yes. This flag is tested by code in an external class `VisibilityUtils` that checks if the bounding boxes of the transformed source and the screen intersect, i.e. independent of the kind of source.  I find it important to understand that this check is also an approximation but it has only false positives if the bounding box of the source is correct.  The case that the source has infinite support (e.g. functions such as this https://github.com/saalfeldlab/imglib2-sandbox/blob/master/src/main/java/net/imglib2/sandbox/JuliaSet.java) was not covered.

**Pull request merged**
