### PR TITLE
Hdf5 types

### PR DESCRIPTION
**Pull request by tpietzsch**
This addresses #154, adding more datatypes to `Hdf5ImageLoader`

For this to work, the datatype must be added as an attribute to each setup group. E.g., the info (pyramid resolutions, etc) for the first setup is under group "/s00" in the h5 file. If "/s00" has a "dataType" string attribute with value "uint8", that means that the datasets for this setup are `UnsignedByteType`.
The values for the "dataType" attribute are the same as for N5. See [DataType](https://github.com/saalfeldlab/n5/blob/697c596bdd30ae9f8884f58b3f2a9643c82e1af4/src/main/java/org/janelia/saalfeldlab/n5/DataType.java#L45-L54) labels and `toString()`.

If no "dataType" attribute is present, it is assumed that the datasets for this setup are legacy `UnsignedShortType`-stored-as-`INT16`.

Supported datatypes ("dataType" attribute values) are:
"int8" (`ByteType`),
"uint8" (`UnsignedByteType`),
"int16" (`ShortType`),
"uint16" (`UnsignedShortType`),
"int32" (`IntType`),
"uint32" (`UnsignedIntType`),
"int64" (`LongType`),
"uint64" (`UnsignedLongType`),
"float32" (`FloatType`),
"float64" (`DoubleType`)

@tischi, @StephanPreibisch Could you test/review this?

There are two open issues:
* HDF5 export should be updated to support more datatypes (it still does the legacy thing).
* The old `Hdf5ImageLoader` respected `ImgLoaderHints.LOAD_COMPLETELY` to load datasets fully into an ArrayImg if possible. This is not supported currently, but I don't know how relevant it still is. 

I'll create separate issues for those.

### CODE REVIEW

**Comment by mkitti** [comment]
https://docs.hdfgroup.org/hdf5/develop/group___p_d_t_s_t_d.html

I wonder if STD data types might be better than NATIVE ?

**Comment by tpietzsch** [comment]
> https://docs.hdfgroup.org/hdf5/develop/group___p_d_t_s_t_d.html
> 
> I wonder if STD data types might be better than NATIVE ?

Can you be a bit more specific?

**Comment by constantinpape** [comment]
@tischi: yes, I have python code that can write this. I had to adapt it a bit though in order to write the dtype metadata, see https://github.com/constantinpape/pybdv/pull/49. 

I have created an example file, will send you the location via embl chat.

**Comment by tischi** [comment]
@constantinpape your `uint64` example image opens, but it is a bit hard to judge whether it opens correctly, due to the contrast limits.

image

Do you happen to know the value range?

**Comment by constantinpape** [comment]
> Do you happen to know the value range?

The value range is 0 to 4294967437. (I offset the non-zero values with the uint32 max id to have actual uint64 data).

I have added `test-data-uint64-v2.xml` in the same folder without these offsets, where the max value is 133, in case that helps.

**Comment by tischi** [comment]
ok, this works:

```
min = 4294967295
max = 4294967437
```

image

@tpietzsch Looks like it works (at least for `uint64` written from python) 🥳

**Comment by tpietzsch** [comment]
@tischi Great!

BTW, do you know that you can set the range on the sliders when you click on the small numbers on the right?

Screenshot 2023-01-17 at 21 22 21

**Comment by tpietzsch** [comment]
> HDF5 export should be updated to support more datatypes (it still does the legacy thing).

This is done now. https://github.com/bigdataviewer/bigdataviewer_fiji/pull/31

**Pull request merged**
