### PR TITLE
Optionally position source name below coordinates

### PR DESCRIPTION
**Pull request by tischi**
Addresses #109

I realised that positioning the source and group names below the coordinates does an even better job in terms of not clashing with them than left alignment. 

It has the additional benefit of keeping out of the way of the multi-box overlay. 

I also like visually that all the text information is shown as one block.

`Prefs.positionTextOverlayBelowCoordinates( true );`

image

I don't really like the name `positionTextOverlayBelowCoordinates` as it is very verbose, but I did not have a shorter idea right now.

What do you think?

### CODE REVIEW

**Comment by tischi** [comment]
I am thinking now nicer could be something like

```
enum TextOverlayLayout {
    TopCenter, // the default, as it used to be
    TopRight // aligned with the position and time point overlays as I implemented it
}

Prefs.textOverlayLayout( TextOverlayLayout layout );
```

This would also allow us to readily add other modalities, if needed.
If you like this better as well I would modify the PR accordingly.

**Comment by tischi** [comment]
@tpietzsch 
cc @NicoKiaru
1. any chance we could merge this PR before the webinar next week?
2. any chance we could also add information about the grey values at the current mouse cursor position? I think if we want to get more people to use BDV for their daily work that would be a must have. I know that this is not entirely trivial as BDV could also should non-numerical sources, given an appropriate `Converter`, but maybe one could check whether the Source is of `RealType` and then show the grey values?

**Comment by NicoKiaru** [comment]
>     2\. any chance we could also add information about the grey values at the current mouse cursor position?

It would be nice but that's not possible in my opinion before the webinar. + I'm going to show a dataset with thousands of sources... What do you display in this case ?

**Comment by tischi** [comment]
> I'm going to show a dataset with thousands of sources... What do you display in this case ?

Good point, looks like this is a more complex issue indeed. So let' leave it for future consideration.
It was also a mistake of mine to clutter this PR with this topic. Sorry.

**Comment by tpietzsch** [comment]
> I am thinking now nicer could be something like
> 
> ```
> enum TextOverlayLayout {
>     TopCenter, // the default, as it used to be
>     TopRight // aligned with the position and time point overlays as I implemented it
> }
> 
> Prefs.textOverlayLayout( TextOverlayLayout layout );
> ```

I changed it to be something like that, cleaned up a bit, etc.

**Comment by tischi** [comment]
Thanks!

**Pull request merged**
