### PR TITLE
Bump jhdf5 to version 19.04.0

### PR DESCRIPTION
**Pull request by mkitti**
This updates the jhdf5 library to version 19.04.0 per https://github.com/scijava/pom-scijava/issues/181

### CODE REVIEW

**Comment by mkitti** [comment]
Are there any other automated CI testing we can run to verify the build?

**Comment by tpietzsch** [comment]
I'm trying to open a HDF5 dataset.
I get this exception:
```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at bdv.img.hdf5.HDF5AccessHack.<init>(HDF5AccessHack.java:142)
	at bdv.img.hdf5.Hdf5ImageLoader.open(Hdf5ImageLoader.java:207)
	at bdv.img.hdf5.Hdf5ImageLoader.getSetupImgLoader(Hdf5ImageLoader.java:381)
	at bdv.img.hdf5.Hdf5ImageLoader.getSetupImgLoader(Hdf5ImageLoader.java:79)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:262)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:294)
	at bdv.BigDataViewer.open(BigDataViewer.java:488)
	at bdv.BigDataViewer.open(BigDataViewer.java:506)
	at bdv.BigDataViewer.main(BigDataViewer.java:753)
```

This is caught here: https://github.com/bigdataviewer/bigdataviewer-core/blob/d6edacb661291ef5d6b78df1cd9a1b8045553052/src/main/java/bdv/img/hdf5/Hdf5ImageLoader.java#L205-L213
and falls back to `HDF5Access` (instead of the faster `HDF5AccessHack`).

Did you forget to commit something? Should I try to fix this (might be trivial)?

**Comment by mkitti** [comment]
Hmm, let me see if I can reproduce this.

**Comment by mkitti** [comment]
After I change some ints to long in https://github.com/bigdataviewer/bigdataviewer-core/pull/131/commits/7e2642c80e424dade22d0428886da45729013d76 I can load data.

**Comment by mkitti** [comment]
Let me know if this works better for reading.

I'm trying to see if the export will work better, but it looks much more complicated.

**Comment by tpietzsch** [comment]
This is now released, with bigdataviewer-core-10.3.1

**Pull request merged**
